import { PostData } from '../types/Post';

const sampleThoughts = [
  "Can't sleep again. The city never really goes quiet, does it?",
  "Je pense trop la nuit. Mes pensées tournent en rond.",
  "Why do the best conversations happen at 3am?",
  "The moon looks different tonight. More distant somehow.",
  "Scrolling endlessly but nothing fills the void inside.",
  "Coffee at midnight was a mistake. But here we are.",
  "Sometimes I wonder if anyone else feels this lost.",
  "Rain against the window. Perfect soundtrack for overthinking.",
  "Es ist 2 Uhr morgens und ich kann nicht schlafen.",
  "That conversation from 5 years ago is replaying again.",
  "The weight of tomorrow feels heavier in the dark.",
  "Why do I always remember the things I want to forget?",
  "Insomnia is just your brain refusing to let go of the day.",
  "The silence is so loud it hurts.",
  "Watching the clock change from 11:59 to 12:00. Another day.",
  "My thoughts are like moths drawn to the flame of consciousness.",
  "The darkness outside mirrors the darkness within.",
  "Sleep is just death being shy, someone once said.",
  "Midnight snacks hit different when you're questioning everything.",
  "The world feels smaller at night. More intimate.",
  "Why do I feel more myself when everyone else is asleep?",
  "Staring at the ceiling has become my meditation.",
  "The night shift of the soul is always hiring.",
  "Dreams feel more real than reality sometimes.",
  "3am thoughts are either profound or completely insane.",
  "The quiet hours reveal truths the daylight hides.",
  "Loneliness is loudest when the world goes silent.",
  "Night time is when the masks come off.",
  "The stars are just holes in the darkness, letting light through.",
  "Sleep deprivation is my natural state now.",
  "Why do problems feel bigger in the dark?",
  "The night is honest in ways the day never is.",
  "Counting sheep is overrated. I count regrets instead.",
  "The darkness doesn't judge. It just listens.",
  "Midnight clarity hits different than morning wisdom.",
  "The night shift workers of the mind never clock out.",
  "Shadows dance differently when you're tired enough.",
  "The quiet hours are when the soul speaks loudest.",
  "Insomnia: when your brain decides to host a late-night talk show.",
  "The moon is the only witness to these thoughts.",
  "Night time is when the real conversations begin.",
  "The darkness is a canvas for overthinking.",
  "Sleep is for people who don't have racing minds.",
  "The night reveals what the day conceals.",
  "Midnight musings are the most honest kind.",
  "The quiet hours are when we meet ourselves.",
  "Darkness is just light taking a break.",
  "The night shift of consciousness never ends.",
  "Sleepless nights are when the soul does its deepest work.",
  "The darkness holds space for thoughts too fragile for daylight.",
  "Night time is when the inner critic works overtime.",
  "The quiet hours are when we process the day's chaos.",
  "Midnight thoughts are unfiltered and raw.",
  "The darkness is a sanctuary for the sleepless.",
  "Night time is when the heart speaks its truth.",
  "The quiet hours reveal the poetry in pain.",
  "Sleepless nights are when we confront our shadows.",
  "The darkness is where thoughts go to be born.",
  "Night time is when the soul does its accounting.",
  "The quiet hours are when we meet our authentic selves.",
  "Midnight musings are the most vulnerable kind.",
  "The darkness holds space for what we can't say in daylight.",
  "Night time is when the inner world comes alive.",
  "The quiet hours are when we process our deepest fears.",
  "Sleepless nights are when we do our most honest thinking.",
  "The darkness is a refuge for the overwhelmed mind.",
  "Night time is when the heart's whispers become audible.",
  "The quiet hours are when we confront our truths.",
  "Midnight thoughts are unguarded and real.",
  "The darkness is where vulnerability feels safe.",
  "Night time is when the soul's voice gets louder.",
  "The quiet hours are when we meet our inner child.",
  "Sleepless nights are when we do our deepest healing.",
  "The darkness holds space for what daylight can't handle.",
  "Night time is when the masks we wear start to slip.",
  "The quiet hours are when we process our grief.",
  "Midnight musings are the soul's way of speaking.",
  "The darkness is where thoughts go to find their voice.",
  "Night time is when the heart does its heaviest lifting.",
  "The quiet hours are when we confront our mortality.",
  "Sleepless nights are when we meet our deepest selves.",
  "The darkness is a sanctuary for the broken-hearted.",
  "Night time is when the soul's wounds feel most tender.",
  "The quiet hours are when we process our shame.",
  "Midnight thoughts are the mind's way of decluttering.",
  "The darkness holds space for what we're afraid to feel.",
  "Night time is when the inner critic gets loudest.",
  "The quiet hours are when we confront our regrets.",
  "Sleepless nights are when we do our most important work.",
  "The darkness is where healing happens in secret.",
  "Night time is when the soul's hunger becomes apparent.",
  "The quiet hours are when we meet our shadow self.",
  "Midnight musings are the heart's way of processing.",
  "The darkness is where thoughts go to transform.",
  "Night time is when the deepest truths surface.",
  "The quiet hours are when we confront our loneliness.",
  "Sleepless nights are when we do our most honest reflecting.",
  "The darkness holds space for what we can't yet understand.",
  "Night time is when the soul's questions become urgent.",
  "The quiet hours are when we process our disappointments.",
  "Midnight thoughts are the mind's way of making sense.",
  "The darkness is where wisdom is born from suffering.",
  "Night time is when the heart's needs become clear.",
  "The quiet hours are when we meet our future selves.",
  "Sleepless nights are when we do our most necessary thinking.",
  "The darkness is a cocoon for transformation.",
  "Night time is when the soul's purpose becomes visible.",
  "The quiet hours are when we confront our dreams.",
  "Midnight musings are the spirit's way of communicating.",
  "The darkness holds space for what we're becoming."
];

const languages = ['en', 'fr', 'de', 'es', 'it', 'pt', 'ru', 'ja', 'ko', 'zh'];

export const generateSamplePosts = (): PostData[] => {
  const posts: PostData[] = [];
  const now = new Date();
  
  for (let i = 0; i < 100; i++) {
    const hoursAgo = Math.floor(Math.random() * 720); // Random time within last 30 days
    const timestamp = new Date(now.getTime() - (hoursAgo * 60 * 60 * 1000));
    const language = Math.random() < 0.8 ? 'en' : languages[Math.floor(Math.random() * languages.length)];
    
    posts.push({
      id: `sample-${i}`,
      content: sampleThoughts[i],
      language,
      timestamp,
      isBookmarked: Math.random() < 0.1 // 10% chance of being bookmarked
    });
  }
  
  return posts.sort((a, b) => b.timestamp.getTime() - a.timestamp.getTime());
};